//
// Created by Fedor Bondarev on 26.04.2023.
//

#ifndef ITMO_C_PNG_FEDORBONDAREV_LIB_DEFLATE_DECOMPRESSOR_DEFLATE_DECOMPRESSOR_H_
#define ITMO_C_PNG_FEDORBONDAREV_LIB_DEFLATE_DECOMPRESSOR_DEFLATE_DECOMPRESSOR_H_

#define DEFLATE_DECOMPRESSOR_SUCCESS 0
#define DEFLATE_DECOMPRESSOR_ERROR_DATA_INVALID 2
#define DEFLATE_DECOMPRESSOR_ERROR_OUT_OF_MEMORY 3
#define DEFLATE_DECOMPRESSOR_ERROR_UNKNOWN 4

int DecompressData(unsigned char *in, unsigned int in_size, unsigned char *out, unsigned long long target_out_size);

#endif	  // ITMO_C_PNG_FEDORBONDAREV_LIB_DEFLATE_DECOMPRESSOR_DEFLATE_DECOMPRESSOR_H_
